### ISSUE TITLE
list 데이터 화면 출력하기

### ISSUE THREAD

**Issue by hyejj19** [hyejj19/coding-test-blog#14]
### TODO

- [x] SWR 라이브러리 설치
- [x] fetch 훅 작성하기
- [x] 리스트 데이터 PostListItem 컴포넌트에 props로 전달
- [x] PostListItem 컴포넌트 수정하여 화면에 출력
