### ISSUE TITLE
issue : 배포하기

### ISSUE THREAD

**Issue by hyejj19** [hyejj19/coding-test-blog#38]
### description

프로젝트 배포하기

### subtasks

- [x] vercel 활용하여 배포하기
- [x] api 요청 404 에러 해결하기 
- [x] 이미지 경로 문제 해결하기
