### ISSUE TITLE
issue : 리드미 작성하기

### ISSUE THREAD

**Issue by hyejj19** [hyejj19/coding-test-blog#40]
### description

과제 리드미 작성하기

### subtasks

- [ ] 실행 방법
- [ ] 사용한 기술 스택
- [ ] 진행 방식 (이슈, 브랜치 전략 등)
- [ ] 각 기능별 세부 내용 간략히
- [ ] DEMO 첨부
- [ ] 기타 등등
